# Generated by Django 5.2.6 on 2025-09-27 19:14

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Sarlavha', max_length=255)),
                ('title_uz', models.CharField(db_index=True, help_text='Sarlavha', max_length=255, null=True)),
                ('title_ru', models.CharField(db_index=True, help_text='Sarlavha', max_length=255, null=True)),
                ('title_en', models.CharField(db_index=True, help_text='Sarlavha', max_length=255, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Rasm (ixtiyoriy)', null=True, upload_to='posts/')),
                ('description', models.TextField(help_text="Batafsil ma'lumot")),
                ('description_uz', models.TextField(help_text="Batafsil ma'lumot", null=True)),
                ('description_ru', models.TextField(help_text="Batafsil ma'lumot", null=True)),
                ('description_en', models.TextField(help_text="Batafsil ma'lumot", null=True)),
                ('status', models.BooleanField(default=True, help_text="Aktiv yoki yo'q")),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text="E'lon qilingan sana")),
                ('type', models.CharField(choices=[('news', 'Yangilik'), ('announcement', "E'lon")], default='news', help_text='Turini tanlang', max_length=20)),
            ],
            options={
                'verbose_name': "Post (Yangilik/E'lon)",
                'verbose_name_plural': "Postlar (Yangiliklar va E'lonlar)",
                'db_table': 'posts',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['status'], name='posts_status_bd5975_idx'), models.Index(fields=['type'], name='posts_type_97ace5_idx'), models.Index(fields=['published_date'], name='posts_publish_fab934_idx')],
            },
        ),
    ]
