# Generated by Django 5.2.6 on 2025-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_page_menus_page_title_e91409_idx_and_more'),
        ('posts', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pages',
            field=models.ManyToManyField(blank=True, help_text='Post qaysi sahifalarga tegishli', null=True, related_name='posts', to='menus.page'),
        ),
    ]
