# Generated by Django 5.2.6 on 2025-12-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_page_type'),
        ('posts', '0005_alter_post_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pages',
            field=models.ManyToManyField(blank=True, help_text='Post qaysi sahifalarga tegishli', related_name='posts', to='menus.page'),
        ),
    ]
