# Generated by Django 5.2.6 on 2025-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
