# Generated by Django 5.2.6 on 2026-01-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_uz', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='collaborations/')),
                ('link', models.URLField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
