# Generated by Django 5.2.6 on 2025-12-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stat_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='stat_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='stat_3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='stat_4',
            field=models.CharField(max_length=50),
        ),
    ]
