# Generated by Django 5.2.6 on 2026-01-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_company_stat_1_alter_company_stat_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to='company_logos/'),
        ),
    ]
