# Generated by Django 5.2.6 on 2025-10-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('title_uz', models.CharField(db_index=True, max_length=200, null=True)),
                ('title_ru', models.CharField(db_index=True, max_length=200, null=True)),
                ('title_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menu')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('title_uz', models.CharField(db_index=True, max_length=200, null=True)),
                ('title_ru', models.CharField(db_index=True, max_length=200, null=True)),
                ('title_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('department', 'Bo‘lim'), ('faculty', 'Kafedra'), ('lab', 'Laboratoriya'), ('page', 'Sahifa')], db_index=True, default='page', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('menu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='menus.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('full_name_uz', models.CharField(db_index=True, max_length=200, null=True)),
                ('full_name_ru', models.CharField(db_index=True, max_length=200, null=True)),
                ('full_name_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('position', models.CharField(db_index=True, max_length=200)),
                ('position_uz', models.CharField(db_index=True, max_length=200, null=True)),
                ('position_ru', models.CharField(db_index=True, max_length=200, null=True)),
                ('position_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('pages', models.ManyToManyField(blank=True, db_index=True, related_name='employees', to='menus.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('title_uz', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('file', models.FileField(help_text='Fayl', upload_to='employee_files/')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.BooleanField(default=True)),
                ('page', models.ForeignKey(help_text='Fayl tegishli xodim', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='menus.page')),
            ],
            options={
                'verbose_name': 'Page Fayli',
                'verbose_name_plural': 'Page Fayllari',
                'db_table': 'page_files',
            },
        ),
        migrations.CreateModel(
            name='PageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Rasm', upload_to='page_images/')),
                ('page', models.ForeignKey(help_text='Paga tegishli rasm', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menus.page')),
            ],
            options={
                'verbose_name': 'Post Rasmi',
                'verbose_name_plural': 'Post Rasmlari',
                'db_table': 'page_images',
            },
        ),
    ]
