# Generated by Django 5.2.6 on 2025-10-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='has_page',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
