# Generated by Django 5.2.6 on 2025-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_page_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('full_name_uz', models.CharField(max_length=200, null=True)),
                ('full_name_ru', models.CharField(max_length=200, null=True)),
                ('full_name_en', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200)),
                ('position_uz', models.CharField(max_length=200, null=True)),
                ('position_ru', models.CharField(max_length=200, null=True)),
                ('position_en', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('pages', models.ManyToManyField(blank=True, related_name='employees', to='menus.page')),
            ],
        ),
    ]
