# Generated by Django 5.2.6 on 2025-11-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_has_page'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['title', 'type', 'status'], name='menus_page_title_e91409_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['title_uz', 'title_ru', 'title_en'], name='page_trans_titles_idx'),
        ),
    ]
