# Generated by Django 5.2.6 on 2025-10-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_uz',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pages',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='employees', to='menus.page'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_uz',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Fayl', upload_to='employee_files/')),
                ('page', models.ForeignKey(help_text='Fayl tegishli xodim', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='menus.page')),
            ],
            options={
                'verbose_name': 'Page Fayli',
                'verbose_name_plural': 'Page Fayllari',
                'db_table': 'page_files',
            },
        ),
    ]
