# Generated by Django 5.2.6 on 2025-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_page_menus_page_title_e91409_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('department', 'Bo‘lim'), ('faculty', 'Kafedra'), ('lab', 'Laboratoriya'), ('page', 'Sahifa'), ('scientific_direction', 'Ilmiy yo‘nalish'), ('postgraduate_education', "Oliy ta'limdan keyingi ta'lim")], db_index=True, default='page', max_length=30),
        ),
    ]
