# Generated by Django 5.2.6 on 2025-12-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='direction',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='sub_title',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
