# Generated by Django 5.2.6 on 2025-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_employee_full_name_alter_employee_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefiles',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagefiles',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
