# Generated by Django 5.2.6 on 2025-12-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_page_direction_page_duration_page_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
