# Generated by Django 5.2.6 on 2025-10-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_pagefiles_position_pagefiles_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AddField(
            model_name='pagefiles',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='menus.menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('department', 'Bo‘lim'), ('faculty', 'Kafedra'), ('lab', 'Laboratoriya'), ('page', 'Sahifa')], default='page', max_length=20),
        ),
    ]
