# Generated by Django 5.2.6 on 2025-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_remove_menu_slug_remove_menu_url_pagefiles_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
