# Generated by Django 5.2.6 on 2025-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_page_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='direction_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='direction_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='direction_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='sub_title_en',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='sub_title_ru',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='sub_title_uz',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
