# Generated by Django 5.2.6 on 2025-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_employee_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefiles',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagefiles',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagefiles',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
