# Generated by Django 5.2.6 on 2025-12-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_page_direction_en_page_direction_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
