# Generated by Django 5.2.6 on 2025-12-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_alter_page_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='duration_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='duration_ru',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='duration_uz',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
