# Generated by Django 5.2.6 on 2026-01-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_page_duration_en_page_duration_ru_page_duration_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('department', 'Bo‘lim'), ('faculty', 'Kafedra'), ('lab', 'Laboratoriya'), ('leadership', 'Rahbariyat'), ('page', 'Sahifa'), ('scientific_direction', 'Ilmiy yo‘nalish'), ('postgraduate_education', "Oliy ta'limdan keyingi ta'lim")], db_index=True, default='page', max_length=30),
        ),
    ]
