# Generated by Django 5.2.6 on 2026-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_alter_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_menu_page',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
